/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import javax.swing.JDialog;
import javax.swing.Timer;
import library.javaToast;
import library.PlayFair;

/**
 *
 * @author milstrike
 */
public class Main extends javax.swing.JFrame {
    
    private int method;
    private int checkerStatus = 0;
    private String key;
    private String jtiskey;
    private String result;
    private final PlayFair pf = new PlayFair();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initLevel0();
        initLevel1();
    }
    
    private void initLevel0(){
        setLocationRelativeTo(null);
    }
    
    private void initLevel1(){
        radEnc.setSelected(true);
        radDec.setSelected(false);
        method = 0;
    }
    
    private int keyChecker(){
        char[] inputArray = varInputKey.getText().toCharArray();
            if(inputArray.length < 6){
                checkerStatus = 0;
            }
            else{
                key = varInputKey.getText();
                checkerStatus = 1;
            }
        return checkerStatus;
    }
    
    private void jtisGetter(){
        String jt = inputJtis.getSelectedItem().toString();
        if(jt.equalsIgnoreCase("Yes")){
            jtiskey = "Y";
        }
        else{
            jtiskey = "N";
        }
    }
    
    private void clipboardCopier(String texte){
        StringSelection stringSelection = new StringSelection(texte);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }
    
    private void showToast(String message){
        final JDialog dialog = new javaToast(Main.this, true, message);
                Timer timer = new Timer(javaToast.LENGTH_SHORT, (ActionEvent e) -> {
                    dialog.setVisible(false);
                    dialog.dispose();
        });
                timer.setRepeats(false);
                timer.start();
 
                dialog.setVisible(true); // if modal, application will pause here
    }
    
    private void EncodeText(){
        keyChecker();
        jtisGetter();
        if(checkerStatus < 1){
            showToast("The key must be at least 6 characters long");
        }
        else{
            result = pf.TextEncoder(key, inputValue.getText(), jtiskey);
            char[] x = result.toCharArray();
            result = "";
            for(int i = 0; i < x.length; i++){
                if(i%2 == 0){
                    if(i == 0){
                        result = result + x[i];
                    }
                    else{
                        result = result + " " + x[i];
                    }
                }
                else{
                    result = result + x[i];
                }
            }
            outputValue.setText(result);
        }
    }
    
    private void DecodeText(){
        keyChecker();
        jtisGetter();
        if(checkerStatus < 1){
            showToast("The key must be at least 6 characters long");
        }
        else{
            result = pf.TextDecoder(key, inputValue.getText().replaceAll("\\s+",""), jtiskey);
            outputValue.setText(result);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radEnc = new javax.swing.JRadioButton();
        radDec = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        varInputKey = new javax.swing.JTextField();
        labeljtis = new javax.swing.JLabel();
        inputJtis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputValue = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputValue = new javax.swing.JTextArea();
        btnStart = new javax.swing.JButton();
        btnCopyOutput = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("PLAYFAIR ENCRYPTION / DECRYPTION TOOLS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/x-mark-16.png"))); // NOI18N
        jLabel2.setToolTipText("Exit App");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Select Method:");

        radEnc.setBackground(new java.awt.Color(51, 51, 51));
        radEnc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        radEnc.setForeground(new java.awt.Color(204, 204, 204));
        radEnc.setText("Encryption");
        radEnc.setToolTipText("");
        radEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEncActionPerformed(evt);
            }
        });

        radDec.setBackground(new java.awt.Color(51, 51, 51));
        radDec.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        radDec.setForeground(new java.awt.Color(204, 204, 204));
        radDec.setText("Decryption");
        radDec.setToolTipText("");
        radDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Key (6 character minimum):");

        varInputKey.setBackground(new java.awt.Color(102, 102, 102));
        varInputKey.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        varInputKey.setForeground(new java.awt.Color(204, 204, 204));

        labeljtis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labeljtis.setForeground(new java.awt.Color(204, 204, 204));
        labeljtis.setText("Replace J with I:");

        inputJtis.setBackground(new java.awt.Color(102, 102, 102));
        inputJtis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputJtis.setForeground(new java.awt.Color(204, 204, 204));
        inputJtis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Input Text:");

        outputValue.setBackground(new java.awt.Color(102, 102, 102));
        outputValue.setColumns(20);
        outputValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        outputValue.setForeground(new java.awt.Color(204, 204, 204));
        outputValue.setLineWrap(true);
        outputValue.setRows(5);
        jScrollPane1.setViewportView(outputValue);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Output Text:");

        inputValue.setBackground(new java.awt.Color(102, 102, 102));
        inputValue.setColumns(20);
        inputValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        inputValue.setForeground(new java.awt.Color(204, 204, 204));
        inputValue.setLineWrap(true);
        inputValue.setRows(5);
        jScrollPane2.setViewportView(inputValue);

        btnStart.setBackground(new java.awt.Color(102, 102, 102));
        btnStart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(204, 204, 204));
        btnStart.setText("Start!");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnCopyOutput.setBackground(new java.awt.Color(102, 102, 102));
        btnCopyOutput.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCopyOutput.setForeground(new java.awt.Color(204, 204, 204));
        btnCopyOutput.setText("Copy Output");
        btnCopyOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyOutputActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(204, 204, 204));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("About");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varInputKey))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labeljtis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputJtis, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(radEnc)
                                .addGap(18, 18, 18)
                                .addComponent(radDec))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCopyOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStart))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radEnc)
                    .addComponent(radDec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(varInputKey, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeljtis)
                    .addComponent(inputJtis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnCopyOutput)
                    .addComponent(btnReset)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void radEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEncActionPerformed
        radDec.setSelected(false);
        radEnc.setSelected(true);
        method = 0;
    }//GEN-LAST:event_radEncActionPerformed

    private void radDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDecActionPerformed
        radEnc.setSelected(false);
        radDec.setSelected(true);
        method = 1;
    }//GEN-LAST:event_radDecActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if(method == 0){
            EncodeText();
        }
        else{
            DecodeText();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnCopyOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyOutputActionPerformed
        clipboardCopier(outputValue.getText());
        showToast("Output Copied");
    }//GEN-LAST:event_btnCopyOutputActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        initLevel1();
        inputValue.setText(null);
        outputValue.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopyOutput;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> inputJtis;
    private javax.swing.JTextArea inputValue;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labeljtis;
    private javax.swing.JTextArea outputValue;
    private javax.swing.JRadioButton radDec;
    private javax.swing.JRadioButton radEnc;
    private javax.swing.JTextField varInputKey;
    // End of variables declaration//GEN-END:variables
}
